### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by billymohajeri** [billymohajeri/Ruby-Group-Capstone#19]
Hi,

We are a team of 3 members: @Wahaj-Ali, @developertariq, and @billymohajeri 
Team member 1: @Wahaj-Ali 
Team member 2: @billymohajeri 
Team member 3: @developertariq 

[Link](https://github.com/billymohajeri/Ruby-Group-Capstone/projects/1) to the project

**Comment by bobb-Rob** [comment]
## STATUS: CHANGES REQUIRED ♻️
Hi Team, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Required Changes ♻️
Hello Team, You did well setting up Kanban boards according to project requirements. 👏🏾 

- [ ] Amongst the group tasks, you included all tasks except the **_Create a main.rb file that will serve as your console app entry-point._**. Kindly add this missing task as a new task or include it in an existing task.

- [ ] For the task - **_implement methods - member 1_**: The tasks below are some tasks that are missing 👇🏾 
    - Create a Book class in a separate .rb file.
    - Create a Label class with an association to the Item class (in a separate .rb file).
  **_Kindly fix this_**.

- [ ] For the task - **_implement methods - member 2_**: The tasks below are some tasks that are missing 👇🏾 
    - Create MusicAlbum class in a separate .rb file.
    - Create Genre class with an association to the Item class (in a separate .rb file).
  **_Kindly fix this_**.

- [ ] For the task - **_implement methods - member 3_**: The tasks below are some tasks that are missing 👇🏾 
    - Create a Game class in a separate .rb file.
    - Create an Author class with an association to the Item class (in a separate .rb file).
  **_Kindly fix this_**.

**_Please fix the above issues raised and re-submit for review._** 

Overall, you have shared all tasks equally. Well done. 👏🏾 👏🏾 👏🏾 👏🏾 

Cheers and Happy coding!👏👏👏

**Comment by billymohajeri** [comment]
Done, thanks for your review 👍

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 


## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
